name: CI

on: [push, pull_request]

jobs:
  hemtt:
    name: HEMTT
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3.5.0
      with:
        submodules: 'recursive'

    - name: Build with HEMTT
      uses: gruppe-adler/action-release-with-hemtt@3.0.0
      id: build
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ steps.build.outputs.zip_name }}
        path: ${{ steps.build.outputs.release_path }}
